language: node_js

cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - stable

before_script:
  - npm prune
  - npm install -g codeclimate-test-reporter

script:
  - npm run lint
  - npm run test:coverage
  - npm run build

after_success:
  - npm run semantic-release
  - CODECLIMATE_REPO_TOKEN=CODECLIMATE_REPO_TOKEN codeclimate-test-reporter < coverage/lcov.info

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
