sudo: false
language: node_js
node_js:
  - "5.0"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run deploy

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
