sudo: false
language: node_js
node_js:
  - "5.0"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - NODE_ENV=development npm run start
  - NODE_ENV=production npm run start
