sudo: false
language: node_js
node_js:
  - "5.0"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run deploy

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_script:
  - NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
